branches:
  only: 
    - next
matrix:
  include:
    # - stage: "Lint"
    #   language: node_js
    #   os: linux
    #   node_js: "8"
    #   script: cd src && npm run ci.tslint && cd ../demo && npm run ci.tslint
    - stage: "Build webpack and Test"
    #   os: osx
    #   env:
    #     - Webpack="iOS"
    #   osx_image: xcode10.0
    #   language: node_js 
    #   node_js: "8"
    #   jdk: oraclejdk8
    #   before_script:
    #     - pip install six
    #     - cd demo && tns platform add ios@next
    #   script: npm run build.plugin && npm i && tns build ios --bundle --env.uglify
    # - os: linux
    #   language: android
    #   env:
    #     - Webpack="Android"
    #   jdk: oraclejdk8
    #   before_install: nvm install 8.11.4
    #   before_script:
    #     - cd demo && tns platform add android@next
    #   script: npm run build.plugin && npm i && tns build android --bundle --env.uglify --env.snapshot
    # - os: linux
    #   env: 
    #     - BuildAndroid="26"
    #   language: android
    #   jdk: oraclejdk8
    #   before_install: nvm install 8.11.4
    #   before_script:
    #     - cd demo && tns platform add android@next
    #   script:
    #     - npm run build.plugin && npm i && tns build android
    # - os: osx
    #   env: 
    #     - BuildiOS="12.0"
    #     - Xcode="10.0"
    #   osx_image: xcode10.0
    #   language: node_js 
    #   node_js: "8"
    #   jdk: oraclejdk8
    #   before_script:
    #     - pip install six
    #     - cd demo && tns platform add ios@next
    #   script: 
    #     - npm run build.plugin && npm i && tns build ios
      os: linux
      language: android
      dist: precise
      jdk: oraclejdk8
      env: 
        - Android="UnitTests"
      before_script:
        - echo no | android create avd --force -n test -t android-21 -b armeabi-v7a
        - emulator -avd test -no-audio -no-window &
        - android-wait-for-emulator
      before_install:
        - nvm install 8.11.4
      script:
        - cd src && npm i && npm run tsc && npm run tslint && cd ../demo && tns platform add android@next && tns build android
        - travis_wait travis_retry tns test android --justlaunch
    - os: osx
      language: node_js
      node_js: "8"
      jdk: oraclejdk8
      env: 
        - iOS="UnitTests"
      osx_image: xcode10.0
      before_script:
        - sudo pip install --upgrade pip
        - sudo pip install six
      script: 
        - cd src && npm i && npm run tsc && npm run tslint && cd ../demo && tns platform add ios@next && tns build ios
        - travis_wait travis_retry tns test ios --justlaunch

android:
  components:
    - tools
    - tools
    - platform-tools
    - build-tools-28.0.2
    - build-tools-27.0.3
    - android-28
    - extra-android-m2repository
    - sys-img-armeabi-v7a-android-21

install:
    - echo no | npm install -g nativescript@next
    - tns usage-reporting disable
    - tns error-reporting disable
    - cd src
    - npm install tns-core-modules@next -D
    - cd ../demo
    - npm install nativescript-dev-webpack@next -D
    - ./node_modules/.bin/update-ns-webpack --deps
    - npm install tns-core-modules@next -P
    - npm install nativescript-dev-typescript@next -D
    - cd ..
